# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativa', '0002_auto_20171005_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=550)),
                ('documento', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('foto', models.TextField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
            options={
                'verbose_name_plural': 'Productores',
                'verbose_name': 'Productor',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name_plural': 'Tipos de documentos',
                'verbose_name': 'Tipo Documento',
            },
        ),
        migrations.AddField(
            model_name='productor',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productor.TipoDocumento'),
        ),
    ]
