# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
