# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=550)),
                ('zona', models.CharField(max_length=70)),
                ('responsable', models.CharField(max_length=70)),
                ('nit', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cooperativa',
                'verbose_name_plural': 'Cooperativas',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=550)),
                ('documento', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('foto', models.TextField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='productor',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.TipoDocumento'),
        ),
    ]
