# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0002_auto_20171005_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
